version: '3.8'
services:
    db:
        image: 'mongo'
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: vivere
    api:
        build: '.'
        links:
            - 'db'
        depends_on: 
            - db
        ports:
            - 8080:8080