version: '3.8'
services:
    cache:
        image: redis
        container_name: cache
        ports:
            - 6379:${REDIS_PORT}
        command: redis-server --requirepass ${REDIS_PASS}
    db:
        image: mongo
        container_name: db
        ports:
            - 27017:${DB_PORT}
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
            MONGO_INITDB_DATABASE: ${DB_NAME}
        command: mongod --port ${DB_PORT}
    api:
        build: '.'
        container_name: api
        links:
            - cache
            - db
        depends_on: 
            - cache
            - db
        ports:
            - 8080:${PORT}